[project]
name = "dragino-config"
version = "1.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.11.1",
    "pyserial>=3.5",
    "questionary>=2.1.0",
]
